name: build
on: { workflow_dispatch, push: { branches: [main] }, pull_request }
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        attrs:
          - os: ubuntu-24.04
            config_name: eldo 
            cmd: .#nixosConfigurations.eldo.config.system.build.toplevel
          - os: ubuntu-24.04
            config_name: bifrost 
            cmd: .#nixosConfigurations.bifrost.config.system.build.toplevel
          - os: macos-15
            config_name: airbook 
            cmd: .#darwinConfigurations.airbook.system

    # Updated job name to use the config_name and os
    name: nix (${{ matrix.attrs.config_name }} on ${{ matrix.attrs.os }}) # <-- Updated name format
    runs-on: ${{ matrix.attrs.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@master # Consider using a specific tag like @v12 for stability
        with:
          name: fisherrjd
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix --show-trace build ${{ matrix.attrs.cmd }}