name: build
on: { workflow_dispatch, push: { branches: [main] }, pull_request }
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        attrs:
          - os: ubuntu-24.04
            cmd: .#nixosConfigurations.eldo.config.system.build.toplevel
          - os: macos-15
            cmd: .#darwinConfigurations.airbook.system
          
    name: nix (${{ matrix.attrs.os }})
    runs-on: ${{ matrix.attrs.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@master
        with:
          name: fisherrjd
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix --show-trace build ${{ matrix.attrs.cmd }}