name: check for flake updates
on: { workflow_dispatch, schedule: [cron: '0 0 * * *'] }
jobs:
  check-for-updates:
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.NIX_TOKEN }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@master
        with:
          name: jade
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix flake update
      - uses: peter-evans/create-pull-request@v7.0.6
        id: pr
        with:
          delete-branch: true
          author: jade fisher <fisherrjd@gmail.com>
          title: automatic update
          commit-message: automatic update
          branch: automatic-update
          token: ${{ secrets.NIX_TOKEN }}
      - if: ${{ steps.pr.outputs.pull-request-number }}
        run: gh pr merge --auto --squash ${{ steps.pr.outputs.pull-request-url }}
